import { JWT } from 'google-auth-library';

export const getAuth = (): JWT => {
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
        email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL, 
        scopes: [
            'https://www.googleapis.com/auth/spreadsheets',
        ],
    });
  return serviceAccountAuth;
}
